my:
  server: # 上传到服务器需要改这个
    name: https://sdadgz.cn
    uploadPath: '/usr/local/springboot/static/' # 文件下载到哪里，记得屁股加个杠 '/usr/local/springboot/static/'
    imgDir: 'img/'
    fileDir: 'file/'

  file-config:
    uploadPath: '${my.server.uploadPath}'
    staticPath: '/static/' # 访问前缀，不是物理地址
    downloadPath: '${my.server.name}:${server.port}${my.file-config.staticPath}' # 存url到数据库时用的他
    imgUploadPath: '${my.file-config.uploadPath}${my.server.imgDir}'
    fileUploadPath: '${my.file-config.uploadPath}${my.server.fileDir}'

spring:
  datasource:
    url: jdbc:mysql://sdadgz.cn:3307/dhc?serverTimezone=UTC&characterEncoding=utf8
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    username: root
  servlet:
    multipart:
      max-request-size: 5GB
      max-file-size: 5GB
  mvc:
    static-path-pattern: ${my.file-config.staticPath}**
  resources:
    static-locations: file:${my.file-config.uploadPath},classpath:/static

server:
  port: 8002
  ssl:
    key-store: classpath:sdadgz.cn.jks
    key-store-type: JKS

mybatis:
  mapper-locations: mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
    auto-mapping-behavior: full
  type-aliases-package: cn.sdadgz.dhc_springboot.entity,  cn.sdadgz.dhc_springboot.Dto
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true
    auto-mapping-behavior: full
  type-aliases-package: cn.sdadgz.dhc_springboot.entity,  cn.sdadgz.dhc_springboot.Dto

# 日志
logging:
  level:
    root: info
  file:
    name: test.log
    max-size: 10MB
    clean-history-on-start: true